### PR TITLE
Windows portability (fix #16)

### LINKED ISSUE #16: Paths on windows get mangled
I get this error for a very simple test
```
Call to `git diff` failed: (ExitFailure 1,"","error: Could not access 'C:UsersneppordAppDataLocalTempver6F55.golden'\n")
```
It seams like all the "\\" are gone and that it cant find the correct file.

### PR DESCRIPTION
**Pull request by andreasabel**
Windows portability (fix #16).

See README and CHANGELOG for a high-level description of changes.

I am planning to release this as 3.3 (major version), since the logic of interactive running without `stdin` has changes (assumes "yes" now).

### CODE REVIEW

File: Test/Tasty/Silver/Interactive.hs [hunk 1]
```diff
@@ -80,23 +83,28 @@ type DisabledTests = TestPath -> Bool
 
 -- | Like @defaultMain@ from the main tasty package, but also includes the
 -- golden test management capabilities.
+
 defaultMain :: TestTree -> IO ()
```
Comment (phile314) [inline Test/Tasty/Silver/Interactive.hs:87]: If I am not mistaken, if the terminal is not interactive all golden values are updated but the exit code is 0 (aka success). If that is indeed the case, maybe you can mention this in the haddock comment here. E.g. something like this:

> ....
> If a golden test fails, the user can interactively analyse the difference and optionally choose to update the golden value.
>
> NOTE: It is not recommended to use the interactive mode in batch processes like e.g. CI builds, as it may hide failing golden tests.

**Review by phile314 — APPROVED** [review]
Looks good to me :+1: 

I guess it currently returns an exit code of 0 if interactive mode updates a golden value automatically when there is no terminal. I would slightly prefer to return a non-0 exit code, but using interactive mode without a terminal is not really how it is intended to be used in the first place so I don't feel too strongly about that.

And I agree, bumping to version 3.3 is warranted due to the change in behavior.

**Comment by andreasabel** [comment]
@phile314 :
> I guess it currently returns an exit code of 0 if interactive mode updates a golden value automatically when there is no terminal. I would slightly prefer to return a non-0 exit code, but using interactive mode without a terminal is not really how it is intended 

Mmh, you have some point here.  Maybe my design was too much influenced by my wish to test `tasty-silver` interactive mode using CI.  To this end, there needs to be a test case that fails in order to show the diff to the golden value as if asking the user, but we do not want the CI to fail subsequently.

What we really want is to pass the `--accept` flag to such self-tests, but I am hampered by #32 (and maybe #24) here.

The logic implemented in this PR is not good, I see this now.  E.g., in Agda we run the CI in interactive mode with a non-interactive terminal, and we do not want that broken tests get automatically accepted.

I wonder how to proceed this PR.  Maybe it is best to take out the "accept if non-interactive terminal" logic and the respective self-test for now and otherwise merge the PR and release.  
Then, given time, I can revisit the problem of self-testing the interactive mode.  Maybe after solving #32 (or #24).

**Comment by phile314** [comment]
> I wonder how to proceed this PR. Maybe it is best to take out the "accept if non-interactive terminal" logic and the respective self-test for now and otherwise merge the PR and release.

Sounds good to me :+1:

**Comment by andreasabel** [comment]
Pushed a commit that reverts back to the old logic for interactive mode (end-of-input means don't-update-golden-value).

File: Test/Tasty/Silver/Interactive.hs (hunk 1 above)
Comment (andreasabel) [reply Test/Tasty/Silver/Interactive.hs:87]: Reverted this change.

**Comment by andreasabel** [comment]
Bumped to 3.3.  Release candidate at: https://hackage.haskell.org/package/tasty-silver-3.3/candidate

**Comment by andreasabel** [comment]
Published! https://hackage.haskell.org/package/tasty-silver-3.3
